language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "demateus@gmail.com"