language: php
php:
  - 5.4
  - 5.3
  - 5.2

before_install:
  - pecl -q install mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --no-interaction

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "demateus@gmail.com"