language: php
php:
  - "5.4"
  - "5.3"

before_install:
  - pecl -q install mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

notifications:
  email: "demateus@gmail.com"